name: Verify Node

on:
  pull_request:
  push:
    branches:
    - 'renovate/*'

jobs:
  verify-linux:
    name: Verify linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
