name: Verify Windows

on:
  pull_request:
  push:
    branches:
    - 'renovate/*'

jobs:
  verify-windows:
    name: Verify windows
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - name: Setup Node 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - run: npm config set scripts-prepend-node-path true

      - name: Test
        run: yarn test
